stages:
  - test
  - deploy

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

test:
  stage: test
  script:
    - npm install
    - npm run test

deploy_dev:
  stage: deploy
  environment:
    name: dev
    url: https://dev.timecheck.app
  script:
    - ssh timecheck@frontend.timecheck.server.mattcorp.com "cd /home/timecheck/frontend && git checkout master && git fetch --all && git reset --hard origin/master && npm install && npm run build && pm2 restart timecheck && exit"
  only:
    - master
